title: Somendra Tripathi
description: My Personal Blog
author: Somendra Tripathi
logo: https://www.iconfinder.com/icons/379550/analytics_icon
github: https://github.com/Somendratripathi/
about: Data Scientist

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: aboutsom
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
